### apiserver
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tiny-apiserver
  namespace: tiny-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-k8s
      component: apiserver
  template:
    metadata:
      labels:
        app: tiny-k8s
        component: apiserver 
    spec:
      containers:
      - command:
        - kube-apiserver
        - --enable-bootstrap-token-auth=true
        - --client-ca-file=/etc/kubernetes/pki/ca.pem
        - --allow-privileged=true
        - --authorization-mode=Node,RBAC
        - --enable-admission-plugins=NodeRestriction
        - --etcd-servers=http://tiny-etcd-client.tiny-k8s.svc:2379
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --secure-port=6443
        - --service-cluster-ip-range=10.96.0.0/12
        - --tls-cert-file=/etc/kubernetes/pki/apiserver.pem
        - --tls-private-key-file=/etc/kubernetes/pki/apiserver-key.pem
        #- --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
        # - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
        - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
        - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
        - --requestheader-allowed-names=front-proxy-client
        - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
        - --requestheader-extra-headers-prefix=X-Remote-Extra-
        - --requestheader-group-headers=X-Remote-Group
        - --requestheader-username-headers=X-Remote-User
        #  - --service-account-key-file=/etc/kubernetes/pki/sa.pub
        image: registry.aliyuncs.com/google_containers/kube-apiserver:v1.14.3
        imagePullPolicy: IfNotPresent
        name: tiny-apiserver
        volumeMounts:
        - name: kubernetes-certs
          mountPath: /etc/kubernetes/pki/
          readOnly: true
        - name: kubernetes-configs
          mountPath: /etc/kubernetes/configs/
          readOnly: true
      volumes:
      - name: kubernetes-certs
        configMap:
          name: tiny-certs
      - name: kubernetes-configs
        configMap:
          name: tiny-configs

### apiserver svc
---
apiVersion: v1 
kind: Service 
metadata:
  name: tiny-apiserver-svc
  namespace: tiny-k8s
spec:
  type: NodePort 
  selector:
    app: tiny-k8s
    component: apiserver
  ports:
  - name: http 
    port: 6443
    targetPort: 6443
    nodePort: 30443

### controller-manager
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tiny-controller-manager
  namespace: tiny-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-k8s
      component: controller-manager
  template:
    metadata:
      labels:
        app: tiny-k8s
        component: controller-manager
    spec:
      containers:
      - command:
        - kube-controller-manager
        - --authentication-kubeconfig=/etc/kubernetes/configs/admin.conf
        - --authorization-kubeconfig=/etc/kubernetes/configs/admin.conf
        - --bind-address=127.0.0.1
        - --client-ca-file=/etc/kubernetes/pki/ca.pem
        - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.pem
        - --cluster-signing-key-file=/etc/kubernetes/pki/ca-key.pem
        - --controllers=*,bootstrapsigner,tokencleaner
        - --kubeconfig=/etc/kubernetes/configs/admin.conf
        - --leader-elect=false
        - --use-service-account-credentials=true
        - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
        - --root-ca-file=/etc/kubernetes/pki/ca.pem
        #- --service-account-private-key-file=/etc/kubernetes/pki/sa.key
        image: registry.aliyuncs.com/google_containers/kube-controller-manager:v1.14.3
        imagePullPolicy: IfNotPresent
        name: kube-controller-manager
        volumeMounts:
        - name: kubernetes-certs
          mountPath: /etc/kubernetes/pki/
          readOnly: true
        - name: kubernetes-configs
          mountPath: /etc/kubernetes/configs/
          readOnly: true
      volumes:
      - name: kubernetes-certs
        configMap:
          name: tiny-certs
      - name: kubernetes-configs
        configMap:
          name: tiny-configs

### scheduler
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tiny-scheduler
  namespace: tiny-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-k8s
      component: scheduler
  template:
    metadata:
      labels:
        app: tiny-k8s
        component: scheduler
    spec:
      containers:
      - command:
        - kube-scheduler
        - --authentication-kubeconfig=/etc/kubernetes/configs/admin.conf
        - --authorization-kubeconfig=/etc/kubernetes/configs/admin.conf
        - --bind-address=127.0.0.1
        - --kubeconfig=/etc/kubernetes/configs/admin.conf
        - --leader-elect=true
        image: registry.aliyuncs.com/google_containers/kube-scheduler:v1.14.3
        imagePullPolicy: IfNotPresent
        name: kube-scheduler
        volumeMounts:
        - name: kubernetes-certs
          mountPath: /etc/kubernetes/pki/
          readOnly: true
        - name: kubernetes-configs
          mountPath: /etc/kubernetes/configs/
          readOnly: true
      volumes:
      - name: kubernetes-certs
        configMap:
          name: tiny-certs
      - name: kubernetes-configs
        configMap:
          name: tiny-configs
